# Generated by Django 5.1.15 on 2026-09-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la moneda')),
                ('siglas', models.CharField(max_length=10, unique=True, verbose_name='Siglas (ej. USD, PYG)')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Moneda activa?')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['nombre'],
            },
        ),
    ]
