# Generated by Django 5.1.15 on 2026-08-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agregar_usuario', '0002_alter_usuariocliente_id'),
        ('clientes', '0002_alter_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='usuariocliente',
            unique_together={('cliente', 'email')},
        ),
    ]
