"""
Django settings for global_exchange project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jtvi36)u7u!a9q2%!j2!l%*qkg5&we@x$wq1k%86--(*e_v!50'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios.apps.UsuariosConfig',
    'clientes',
    'agregar_usuario',
    'mozilla_django_oidc',
    'authentication',
]

MIDDLEWARE = [
    'authentication.middleware.CanonicalHostMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.RolesMiddleware',
    'authentication.middleware.ClientSelectionMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'authentication.backends.KeycloakOIDCBackend',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'menu'
LOGOUT_REDIRECT_URL = 'login'

# --- Keycloak / OIDC ---
OIDC_RP_CLIENT_ID = os.getenv('OIDC_RP_CLIENT_ID', config('OIDC_RP_CLIENT_ID', default='django-app'))
OIDC_RP_CLIENT_SECRET = os.getenv('OIDC_RP_CLIENT_SECRET', config('OIDC_RP_CLIENT_SECRET', default='maie fyxm kzlx tyur'))
OIDC_RP_SIGN_ALGO = 'RS256'

KEYCLOAK_BASE_URL = os.getenv('KEYCLOAK_BASE_URL', config('KEYCLOAK_BASE_URL', default='http://localhost:8080'))
KEYCLOAK_SERVER_URL = os.getenv('KEYCLOAK_SERVER_URL', config('KEYCLOAK_SERVER_URL', default=KEYCLOAK_BASE_URL))
KEYCLOAK_REALM = os.getenv('KEYCLOAK_REALM', config('KEYCLOAK_REALM', default='global-exchange'))

# Endpoints para el navegador (frontend / auth redirect)
_KEYCLOAK_FRONTEND_ISSUER = f'{KEYCLOAK_BASE_URL}/realms/{KEYCLOAK_REALM}'
OIDC_OP_AUTHORIZATION_ENDPOINT = f'{_KEYCLOAK_FRONTEND_ISSUER}/protocol/openid-connect/auth'
OIDC_OP_LOGOUT_ENDPOINT = f'{_KEYCLOAK_FRONTEND_ISSUER}/protocol/openid-connect/logout'

# Endpoints internos servidor a servidor (token exchange, userinfo, certs)
_KEYCLOAK_BACKEND_ISSUER = f'{KEYCLOAK_SERVER_URL}/realms/{KEYCLOAK_REALM}'
OIDC_OP_TOKEN_ENDPOINT = f'{_KEYCLOAK_BACKEND_ISSUER}/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = f'{_KEYCLOAK_BACKEND_ISSUER}/protocol/openid-connect/userinfo'
OIDC_OP_JWKS_ENDPOINT = f'{_KEYCLOAK_BACKEND_ISSUER}/protocol/openid-connect/certs'

ROOT_URLCONF = 'global_exchange.urls'
OIDC_STORE_ID_TOKEN = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'global_exchange.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', config('DB_NAME', default='global_exchange')),
        'USER': os.getenv('DB_USER', config('DB_USER', default='postgres')),
        'PASSWORD': os.getenv('DB_PASSWORD', config('DB_PASSWORD', default='123456')),
        'HOST': os.getenv('DB_HOST', config('DB_HOST', default='127.0.0.1')),
        'PORT': os.getenv('DB_PORT', config('DB_PORT', default='5432')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media Files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Redis & Cache Configuration (Servidor de Cache)
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')
if os.getenv('USE_REDIS_CACHE', 'False').lower() in ('true', '1', 'yes'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }

# Celery Configuration (Servidor de Tareas Async)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Email Configuration
# Default to console backend during local development / testing, or SMTP when specified
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '1025'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@globalexchange.com')
EMAIL_TOKEN_EXPIRATION_HOURS = int(os.getenv('EMAIL_TOKEN_EXPIRATION_HOURS', '24'))

# Keycloak Integration Settings (Admin REST API)
KEYCLOAK_SERVER_URL = os.getenv('KEYCLOAK_SERVER_URL', 'http://localhost:8080')
KEYCLOAK_REALM = os.getenv('KEYCLOAK_REALM', 'global-exchange')
KEYCLOAK_ADMIN_CLIENT_ID = os.getenv('KEYCLOAK_ADMIN_CLIENT_ID', 'admin-cli')
KEYCLOAK_ADMIN_CLIENT_SECRET = os.getenv('KEYCLOAK_ADMIN_CLIENT_SECRET', '')
KEYCLOAK_ADMIN_USERNAME = os.getenv('KEYCLOAK_ADMIN_USERNAME', 'admin')
KEYCLOAK_ADMIN_PASSWORD = os.getenv('KEYCLOAK_ADMIN_PASSWORD', 'admin')
KEYCLOAK_CLIENT_ID = os.getenv('KEYCLOAK_CLIENT_ID', 'global-exchange-app')
KEYCLOAK_ENABLED = os.getenv('KEYCLOAK_ENABLED', 'True').lower() in ('true', '1', 'yes')

# Base URL for email verification links
APP_BASE_URL = os.getenv('APP_BASE_URL', 'http://127.0.0.1:8000')
