"""
Django settings for global_exchange project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jtvi36)u7u!a9q2%!j2!l%*qkg5&we@x$wq1k%86--(*e_v!50'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clientes',
    'usuarios',
    'agregar_usuario',
    'mozilla_django_oidc',
    'authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.RolesMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'authentication.backends.KeycloakOIDCBackend',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'menu'
LOGOUT_REDIRECT_URL = 'login'

# --- Keycloak / OIDC ---
OIDC_RP_CLIENT_ID = config('OIDC_RP_CLIENT_ID', default='django-app')
OIDC_RP_CLIENT_SECRET = config('OIDC_RP_CLIENT_SECRET', default='CHANGE_ME_IN_ENV')
OIDC_RP_SIGN_ALGO = 'RS256'

KEYCLOAK_BASE_URL = config('KEYCLOAK_BASE_URL', default='http://localhost:8000')
KEYCLOAK_REALM = config('KEYCLOAK_REALM', default='global-exchange')
_KEYCLOAK_ISSUER = f'{KEYCLOAK_BASE_URL}/realms/{KEYCLOAK_REALM}'

OIDC_OP_AUTHORIZATION_ENDPOINT = f'{_KEYCLOAK_ISSUER}/protocol/openid-connect/auth'
OIDC_OP_TOKEN_ENDPOINT = f'{_KEYCLOAK_ISSUER}/protocol/openid-connect/token'
OIDC_OP_USER_ENDPOINT = f'{_KEYCLOAK_ISSUER}/protocol/openid-connect/userinfo'
OIDC_OP_JWKS_ENDPOINT = f'{_KEYCLOAK_ISSUER}/protocol/openid-connect/certs'
OIDC_OP_LOGOUT_ENDPOINT = f'{_KEYCLOAK_ISSUER}/protocol/openid-connect/logout'

ROOT_URLCONF = 'global_exchange.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        
        },
        'DIRS': [BASE_DIR / 'templates'],
    },
]

WSGI_APPLICATION = 'global_exchange.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'global_exchange',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
