# Generated by Django 5.1.15 on 2026-08-31 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_crear_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_id', models.CharField(blank=True, help_text='Identificador único (UUID) asignado por Keycloak', max_length=128, null=True, unique=True, verbose_name='ID en Keycloak')),
                ('estado', models.CharField(choices=[('PENDIENTE_VERIFICACION', 'Pendiente de verificación'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='PENDIENTE_VERIFICACION', max_length=30, verbose_name='Estado de la cuenta')),
                ('email_verificado', models.BooleanField(default=False, verbose_name='Correo verificado')),
                ('token_verificacion', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Token de verificación')),
                ('token_expiracion', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-creado_en'],
            },
        ),
    ]
