# Generated by Django 6.1 on 2026-08-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], max_length=10)),
                ('segmento', models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], default='MINORISTA', max_length=15)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
