# Generated by Django 5.1.15 on 2026-09-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo')], max_length=20)),
                ('entidad', models.CharField(blank=True, help_text='Nombre del Banco o Entidad emisora', max_length=100, null=True)),
                ('numero', models.CharField(blank=True, help_text='Número de cuenta o tarjeta', max_length=50, null=True)),
                ('titular', models.CharField(blank=True, help_text='Nombre del titular', max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_de_pago', to='clientes.cliente')),
            ],
        ),
    ]
