# Generated by Django 5.1.15 on 2026-09-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('PYG', 'Guaraní'), ('ARS', 'Peso Argentino'), ('BRL', 'Real Brasileño')], default='USD', max_length=3, verbose_name='Moneda Origen')),
                ('moneda_destino', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('PYG', 'Guaraní'), ('ARS', 'Peso Argentino'), ('BRL', 'Real Brasileño')], default='PYG', max_length=3, verbose_name='Moneda Destino')),
                ('compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Compra')),
                ('venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
