# Generated by Django 5.1.15 on 2026-09-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacion_registrado_por'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='moneda_destino',
            field=models.ForeignKey(limit_choices_to={'activa': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='cotizaciones_destino', to='monedas.moneda', verbose_name='Moneda Destino'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='moneda_origen',
            field=models.ForeignKey(limit_choices_to={'activa': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='cotizaciones_origen', to='monedas.moneda', verbose_name='Moneda Origen'),
        ),
    ]
